lib/app_web/router.ex
defmodule AppWeb.Router do
  use AppWeb, :router
  use Pow.Phoenix.Router
  use PowAssent.Phoenix.Router

  use Pow.Extension.Phoenix.Router,
    extensions: [PowResetPassword]

  pipeline :skip_csrf_protection do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_secure_browser_headers
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TurbolinksPlug
  end

  pipeline :marketing_layout do
    plug :put_layout, {AppWeb.LayoutView, :marketing}
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  if Mix.env() == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end

  scope "/" do
    pipe_through :skip_csrf_protection

    pow_assent_authorization_post_callback_routes()
  end

  # I want the account edit route to have the app.html layout. The others have the marketing.html layout
  scope "/", Pow.Phoenix, as: "pow" do
    pipe_through [:browser]
    get "/account/edit", RegistrationController, :edit
  end

  # Here I'm just renaming the routes to be more friendly (/register vs /registrations/new)
  scope "/", Pow.Phoenix, as: "pow" do
    pipe_through [:browser, :marketing_layout]
    get "/register", RegistrationController, :new
    post "/register", RegistrationController, :create
    get "/sign-in", SessionController, :new
    post "/sign-in", SessionController, :create
  end

  scope "/" do
    pipe_through [:browser, :marketing_layout]

    pow_routes()
    pow_extension_routes()
    pow_assent_routes()
  end

  scope "/", AppWeb do
    pipe_through [:browser, :marketing_layout]
    get "/", PageController, :index
    get "/pricing", PageController, :pricing
    get "/features", PageController, :features
    get "/privacy", PageController, :privacy
    get "/terms", PageController, :terms
  end

  # Add your protected routes here
  scope "/", AppWeb do
    pipe_through [:browser, :protected]

    get "/app", PageController, :dashboard
  end
end

lib/app_web/views/pow/registration_view.ex
defmodule AppWeb.Pow.RegistrationView do
  use AppWeb, :view
end

lib/app_web/views/pow/session_view.ex
defmodule AppWeb.Pow.SessionView do
  use AppWeb, :view
end

lib/app_web/templates/pow/session/new.html.eex
<%= render_in AppWeb.HelpersView, "_floating_box.html", assigns do %>
  <h2 class="h2">Sign in</h2>

  <div class="my-3">
    <%= PowAssent.Phoenix.ViewHelpers.authorization_link(@conn, "facebook", class: "facebook") %>
  </div>

  <hr class="my-6 text-gray-500" /> 

  <%= form_for @changeset, @action, [as: :user, class: "w-full"], fn f -> %>
    <h3 class="h3 mb-5">Or sign in with email</h3>
    <%= render AppWeb.HelpersView, "_text_input.html", [form: f, field: Pow.Ecto.Schema.user_id_field(@changeset)] %>
    <%= render AppWeb.HelpersView, "_password_input.html", [form: f, field: :password] %>

    <div class="flex items-center justify-between">
      <%= render AppWeb.HelpersView, "_checkbox.html", [form: f, field: :persistent_session, label: "Remember me"] %>

      <div class="text-sm text-blue-500 text-right mb-5">
        <%= link("Forgot your password?", to: Routes.pow_reset_password_reset_password_path(@conn, :new)) %>
      </div>
    </div>
    
    <div class="my-6">
      <%= if @changeset.action do %>
        <%= render AppWeb.HelpersView, "_notification.html", content: "Oops, something went wrong! Please check the form for errors.", color: "red" %>
      <% end %>
    </div>
    
    <div class="flex items-center justify-between">
      <%= submit "Sign in", class: "btn btn-green" %>
      <%= link "Register", to: Routes.pow_registration_path(@conn, :new), class: "text-gray-500 text-sm hover:underline" %>
    </div>
  <% end %>
<% end %>